Fixed a linker issue resulting in undefined reference to Freestyle_Init. The issue was caused by the order of libraries given to the linker.  More specifically, libbf_python.a should precede libbf_freestyle.a, which is assured by choosing an appropriate 'priority' value of a BlenderLib.